services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - "POSTGRES_DB=hometask"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "6432:5432"